/** @type {import('tailwindcss').Config} */
export default {
  darkMode: "class",
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "surface-container-lowest": "#0a0a0a",
        "on-secondary-fixed-variant": "#3b0764",
        "secondary-fixed-dim": "#a78bfa",
        "on-primary-fixed": "#2e1065",
        "surface-variant": "#262626",
        "on-background": "#f3f4f6",
        "surface-dim": "#0e0e0e",
        "on-tertiary": "#1e1b4b",
        "secondary-container": "#5b21b6",
        "background": "#0e0e0e",
        "primary-container": "#6d28d9",
        "surface-container-highest": "#333333",
        "on-primary-container": "#f3e8ff",
        "on-tertiary-container": "#e0e7ff",
        "on-primary-fixed-variant": "#4c1d95",
        "on-surface-variant": "#9ca3af",
        "inverse-on-surface": "#262626",
        "primary-fixed": "#ede9fe",
        "on-tertiary-fixed-variant": "#312e81",
        "surface-container": "#1a1a1a",
        "secondary-fixed": "#ddd6fe",
        "on-tertiary-fixed": "#1e1b4b",
        "tertiary-container": "#4338ca",
        "secondary": "#a78bfa",
        "outline-variant": "#404040",
        "on-error-container": "#ffdad6",
        "surface-tint": "#8b5cf6",
        "surface-bright": "#333333",
        "on-secondary-container": "#f3e8ff",
        "surface-container-low": "#141414",
        "primary-fixed-dim": "#c4b5fd",
        "inverse-surface": "#e5e2e1",
        "tertiary-fixed": "#e0e7ff",
        "on-surface": "#f3f4f6",
        "tertiary-fixed-dim": "#818cf8",
        "inverse-primary": "#4c1d95",
        "on-secondary": "#1e1b4b",
        "error": "#ffb4ab",
        "surface-container-high": "#262626",
        "surface": "#0e0e0e",
        "primary": "#8b5cf6",
        "on-error": "#690005",
        "error-container": "#93000a",
        "tertiary": "#818cf8",
        "outline": "#737373",
        "on-primary": "#ffffff",
        "on-secondary-fixed": "#1e1b4b",
        "accent": "#f4c430",
        "dark": "#0e0e0e",
        /* Explicit Pinnacle Brand Utility Tokens */
        "pinnacle-purple": "#6D28D9",
        "pinnacle-violet": "#8B5CF6",
        "pinnacle-lavender": "#A78BFA",
        "pinnacle-gold": "#F4C430",
        "pinnacle-card": "#141414",
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      spacing: {
        "section-gap": "32px",
        "navbar-height": "64px",
        "container-margin": "24px",
        "card-padding-y": "20px",
        "gutter": "16px",
        "card-padding-x": "24px"
      },
      fontFamily: {
        "headline": ["Outfit", "Space Grotesk", "Inter", "sans-serif"],
        "stat-lg": ["Outfit", "Space Grotesk", "Inter", "sans-serif"],
        "label-md": ["Inter", "sans-serif"],
        "display-lg": ["Outfit", "Space Grotesk", "Inter", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
        "headline-sm": ["Outfit", "Space Grotesk", "Inter", "sans-serif"],
        "body-lg": ["Inter", "sans-serif"],
        "headline-md": ["Outfit", "Space Grotesk", "Inter", "sans-serif"],
        "label-sm": ["Inter", "sans-serif"]
      },
      fontSize: {
        "stat-lg": ["28px", { "lineHeight": "34px", "letterSpacing": "-0.02em", "fontWeight": "700" }],
        "label-md": ["12px", { "lineHeight": "16px", "letterSpacing": "0.05em", "fontWeight": "700" }],
        "display-lg": ["32px", { "lineHeight": "40px", "letterSpacing": "-0.02em", "fontWeight": "700" }],
        "body-md": ["14px", { "lineHeight": "20px", "fontWeight": "400" }],
        "headline-sm": ["20px", { "lineHeight": "28px", "fontWeight": "700" }],
        "body-lg": ["16px", { "lineHeight": "24px", "fontWeight": "400" }],
        "headline-md": ["24px", { "lineHeight": "32px", "letterSpacing": "-0.01em", "fontWeight": "700" }],
        "label-sm": ["11px", { "lineHeight": "14px", "fontWeight": "400" }]
      }
    },
  },
  plugins: [],
}
